### ISSUE TITLE
Remove master branch

### ISSUE THREAD

**Issue by gbinal** [18F/microsite-template-18f#1]
Since this project focuses on the gh-pages branch, my recommendation would be that we remove the `master` branch entirely.  Anyone mind if I do that?    

cc @RobertLRead

**Comment by RobertLRead** [comment]
Sounds great, full speed ahead!

On Thu, Jan 29, 2015 at 11:19 AM, Gray Brooks notifications@github.com
wrote:

> Since this project focuses on the gh-pages branch, my recommendation would
> be that we remove the master branch entirely. Anyone mind if I do that?
> 
> cc @RobertLRead https://github.com/RobertLRead
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/18F/microsite-template-18f/issues/1.

## 

Robert L. Read, PhD
Managing Director, 18F Consulting http://18f.github.io/consulting/
(202) 809-1941

**Comment by gbinal** [comment]
Done.  Thanks!
